---
- hosts: localhost
  remote_user: root
  vars: 
    mysql_root_password: root

  tasks:

#  - name: Stopping the Firewall service
#    service: name=firewalld state=stopped enabled=no

  - selinux:
      state: disabled

  - name: Installing Apache
    yum: state=latest name={{ item }}
    with_items:
    - httpd
    - httpd-devel

  - name: Installing the Database
    yum: state=latest name={{ item }}
    with_items:
    - mariadb
    - mariadb-server

  - name: Installing the repository
    yum: state=installed name={{ item }}
    with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

  - name: Add remi-php72
    shell: yum-config-manager --enable remi-php72

  - name: Installing PHP
    yum: state=latest name={{ item }}
    with_items:
    - php 
    - php-common 
    - php-opcache 
    - php-mcrypt 
    - php-cli 
    - php-gd 
    - php-curl 
    - php-mysqlnd

  - name: Starting the Database
    service: name=mariadb state=started enabled=yes

  - name: delete anonymous MySQL server user for {{ ansible_hostname }}
    action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
 
  - name: delete anonymous MySQL server user for localhost
    action: mysql_user user="" state="absent"
  
  - name: remove the MySQL test database
    action: mysql_db db=test state=absent

  - name: Change root user password on first run
    mysql_user: login_user=root
                login_password=''
                name=root
                password={{ mysql_root_password }}
                priv=*.*:ALL,GRANT
                host={{ item }}
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Executing necessary mysql query for Piwik
    command: >
      mysql --user=root --password={{ mysql_root_password }} << eof
      CREATE DATABASE piwik_data;
      CREATE USER 'piwik'@'localhost' IDENTIFIED BY 'piwik';
      GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON piwik_data.* TO 'piwik'@'localhost';
      FLUSH PRIVILEGES;

  - name: Installing wget
    yum: state=latest name=wget

  - name: Downloading Matomo
    get_url:
      url: https://builds.piwik.org/piwik.zip
      dest: /opt

  - name: Unlinking file
    shell: unzip /opt/piwik.zip -d /var/www/html

  - name: Granting permission to Apache
    shell: chown -R apache:apache /var/www/html/piwik

  - name: Configuring php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: '^;always_populate_raw_post_data = -1'
      line: 'always_populate_raw_post_data = -1'

  - name: Adding GeoIP (Php)
    get_url:
      url: http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
      dest: /var/www/html/piwik/misc

  - name: Unzipping .dat file
    shell: gzip -d /var/www/html/piwik/misc/GeoLiteCity.dat.gz

  - name: Rename .dat file
    shell: mv /var/www/html/piwik/misc/GeoLiteCity.dat /var/www/html/piwik/misc/GeoIPCity.dat

  - name:  SELinux setting for apache user to get access on httpd and db connection
    shell: setsebool -P httpd_unified on
    shell: setsebool -P httpd_can_network_connect_db on 

  - name: Enabling the Apache service
    service: name=httpd state=started enabled=yes
