---

- name: template {{tomcat9_home}}/bin/setenv.sh
  template:
    src: setenv.sh.j2
    dest: "{{tomcat9_home}}/bin/setenv.sh"
  notify: restart tomcat9
  when: ansible_os_family == 'RedHat'

- name: server configuration
  template:
    src: server.xml.j2
    dest: "{{tomcat9_home}}/conf/server.xml"
  notify: restart tomcat9
  sudo: True

- name: template tomcat-users.xml
  template:
    src: tomcat-users.xml.j2
    dest: "{{tomcat9_home}}/conf/tomcat-users.xml"
    owner: "{{ tomcat9_server_user }}"
    group: "{{ tomcat9_server_group }}"
    mode: "640"
  notify: restart tomcat9

- name: start tomcat
  service:
    name: "{{tomcat_service_name}}"
    state: started
    enabled: yes
  sudo: True
